all:
  hosts:
    nova-v3:
      ansible_host: 192.168.2.77
      ansible_user: admin
      ansible_ssh_private_key_file: ~/.ssh/id_ansible_service
      ansible_ssh_common_args: '-o IdentitiesOnly=yes -o StrictHostKeyChecking=no'