---
# ðŸŽ¯ NOVA v3 Ansible Inventory
# Definiert Hosts und Gruppen fÃ¼r Ansible-Playbooks

all:
  children:
    # Samba-Server
    samba_servers:
      hosts:
        samba01:
          ansible_host: 192.168.1.100
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    # YubiKey-Hosts
    yubikey_hosts:
      hosts:
        workstation01:
          ansible_host: 192.168.1.101
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        
        server01:
          ansible_host: 192.168.1.102
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    # NOVA v3 Hosts
    nova_hosts:
      hosts:
        nova-core:
          ansible_host: 192.168.1.110
          ansible_user: nova
          ansible_ssh_private_key_file: ~/.ssh/nova_id_rsa
  
  vars:
    # Global variables
    ansible_python_interpreter: /usr/bin/python3
